Repository derailed/k9s, pull requests merged in 2023-11, with the labels that each got.

#2275 check if the Node already cordoned when executing Drain
  internal/dao/node.go
Labels: question

#2213 fix(#1359): add option to keep missing clusters in config
  README.md
  internal/config/config_test.go
  internal/config/k9s.go
Labels: enhancement, needs-review

#2202 fix: trigger a single log refresh after changing 'since' value
  internal/view/log.go
Labels: bug

#2029 feat: allow for multiple plugin files in $XDG_DATA_DIRS/k9s/plugins
  internal/config/plugin.go
  internal/config/plugin_test.go
  internal/config/testdata/plugins/test1.yml
  internal/config/testdata/plugins/test2.yml
Labels: enhancement

#1445 Add flux plugin image reconciliation commands
  plugins/flux.yml
Labels: enhancement, needs-tlc

#2301 feat: add imagePullSecrets and imagePullPolicy configuration for shellpod
  README.md
  internal/config/shell_pod.go
  internal/view/exec.go
Labels: enhancement, change-requested

#2284 Allow both .yaml and .yml for skin
  internal/config/alias.go
  internal/config/config.go
  internal/config/hotkey.go
  internal/config/plugin.go
  internal/config/styles.go
  internal/config/views.go
  internal/dao/popeye.go
  internal/ui/config.go
Labels: enhancement, change-requested

#2285 add suggestions for context and resources on the command bar
  internal/view/app.go
  internal/view/app_test.go
Labels: enhancement, change-requested

#2319 proper handling of help commands (fixes #2154)
  internal/ui/prompt.go
  internal/ui/prompt_test.go
  internal/view/app.go
Labels: enhancement, InProgress
