Repository derailed/k9s, pull requests merged in 2024-08, with the labels that each got.

#2751 container logs should be escaped when printed
  go.mod
  go.sum
  internal/dao/log_item_test.go
  internal/dao/pod.go
Labels: needs-tlc

#2791 Add leading space to Kubernetes context suggestions
  internal/view/cmd/helpers.go
Labels: bug

#2333 Add color to hpa line when replicas >= maxpods
  internal/model/registry.go
  internal/render/hpa.go
  internal/render/hpa_test.go
Labels: enhancement
