Repository derailed/k9s, pull requests merged in 2024-01, with the labels that each got.

#2314 Update pod status contstants to account for Evicted and ContainerStatusUnknown and leverage them in sanitize
  internal/dao/pod.go
  internal/render/pod.go
Labels: enhancement, question, InProgress, needs-tlc

#2477 shell autocomplete for k8s flags
  cmd/root.go
  internal/client/client.go
Labels: enhancement, question, InProgress

#2480 Adding system arch to nodes view
  internal/render/node.go
  internal/render/node_test.go
Labels: enhancement, question

#2461 Secrets are decoded upon describe
  internal/client/gvr.go
  internal/dao/alias_test.go
  internal/dao/container_test.go
  internal/dao/secret.go
  internal/dao/secret_test.go
  internal/dao/testdata/secret.json
  internal/dao/utils_test.go
  internal/model/describe.go
  internal/model/registry.go
  internal/model/types.go
  internal/view/live_view.go
  internal/view/secret.go
Labels: enhancement, needs-tlc
