Repository derailed/k9s, pull requests merged in 2025-02, with the labels that each got.

#3045 fix: CRD loading: trim group suffix from CRD name
  internal/dao/registry.go
Labels: bug, needs-tlc

#3033 Fix: switch context fails after failed connection
  internal/client/client.go
Labels: bug, needs-tlc

#2799 feat(app): add history navigation with `[` and `]`, most recent command with `-`
  README.md
  internal/model/history.go
  internal/model/history_test.go
  internal/ui/key.go
  internal/view/actions.go
  internal/view/alias.go
  internal/view/app.go
  internal/view/app_test.go
  internal/view/command.go
  internal/view/crd.go
  internal/view/help.go
  internal/view/ns.go
  internal/view/owner_extender.go
  internal/view/pulse.go
  internal/view/reference.go
  internal/view/sanitizer.go
  internal/view/workload.go
  internal/view/xray.go
Labels: enhancement, question

#2965 Make menu foreground style configurable through skins
  README.md
  internal/config/styles.go
  internal/ui/menu.go
  skins/stock.yaml
Labels: enhancement

#2833 allow scaling custom resource
  internal/dao/registry.go
  internal/dao/scalable.go
  internal/dao/types.go
  internal/view/command.go
  internal/view/dp_test.go
  internal/view/scale_extender.go
  internal/view/sts_test.go
  internal/watch/factory.go
Labels: enhancement, question, needs-tlc, conflicts
