Repository derailed/k9s, pull requests merged in 2025-04, with the labels that each got.

#3259 Add plugin to temporarily scale down/up all deployments, statefulsets, and daemonsets in a namespace using szero
  plugins/README.md
  plugins/szero.yaml
Labels: needs-tlc

#3265 plugins: add a plugin to start an alpine:latest container in current context/namespace
  plugins/README.md
  plugins/start-alpine.yaml
Labels: needs-tlc

#3253 fix: set default request timeout to 120 seconds
  cmd/root.go
  internal/client/config.go
Labels: question

#2866 Feature/default_view
  README.md
  cmd/root.go
  internal/config/json/schemas/k9s.json
  internal/config/k9s.go
  internal/config/testdata/configs/default.yaml
  internal/config/testdata/configs/expected.yaml
  internal/config/testdata/configs/k9s.yaml
  internal/config/testdata/configs/k9s_toast.yaml
Labels: enhancement, needs-tlc, conflicts
